# Generated by Django 5.1.1 on 2024-12-17 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='match_invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='match.matchinvitation'),
        ),
    ]
